### ISSUE TITLE
Parameter specified as non-null is null: method h.h2.t.f0.checkNotNullParameter, parameter bundle 运气出现这个错误

### ISSUE THREAD

**Issue by ousq** [gdutxiaoxu/AnchorTask#2]
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method h.h2.t.f0.checkNotNullParameter, parameter bundle
        at c.r.a.g.n$a.onActivityCreated(Unknown Source:7)
        at android.app.Application.dispatchActivityCreated(Application.java:204)
        at android.app.Activity.onCreate(Activity.java:1034)
        at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:154)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:312)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
        at com.trello.rxlifecycle2.components.support.RxAppCompatActivity.onCreate(RxAppCompatActivity.java:59)
       SplashActivity.onCreate(SplashActivity.java:106)

集成之后

**Comment by ousq** [comment]
修改了方式启动时间还是没有 减少
